safe: true
lsi: false
highlighter: rouge
markdown: kramdown
excerpt_separator: "<!--more-->"
exclude: [node_modules, package.json]
destination: public
source: src
collections: [projects]
sass:
  sass_dir: src/_sass
  style: compressed

full_name: Oscar Persson
blog_name: dallaspersson.github.io
url: https://dallaspersson.github.io
image: https://dallaspersson.github.io/assets/images/main.png
square_image: http://dallaspersson.github.io/assets/images/main_square.png
description: >
  Discover things about programming. I am a software engineer, and like the rest
  of us I want to share the things I learn.
twitter_username: '@dallaspersson'
