safe: true
lsi: false
pygments: true
markdown: kramdown
exclude: [node_modules, Gruntfile.js, package.json]
sass:
  sass_dir: _sass
  style: compressed

full_name: Oscar Persson
blog_name: Blog | dallas.persson.github.io
url: http://dallaspersson.github.io
image: http://dallaspersson.github.io/assets/images/main.png
square_image: http://dallaspersson.github.io/assets/images/main_square.png
description: >
  Discover things about programming. I am a software engineer, and like the rest
  of us I want to share the things I learn.
twitter_username: '@dallaspersson'
